### ISSUE TITLE
user and password required

### ISSUE THREAD

**Issue by emichester** [esa-prl/rover-package_set#2]
I don't belong to the staff of the ESA, but I am developing my end-of-degree project doing an algorithm for the Sample Fetching Rover and I need to use this packages within a rock workspace and when I bootstrap (https://github.com/esa-prl/buildconf) the bootstraping process tries to open an ESA private repository (https://gitlab.esa.int/prl/drivers-orogen-autonav_interface.git) and I don't have permission to access it. I've tried several ways to use the perception/stereo and perception/dem_generation packages but there is no luck because there is always a problem. Can you tell me if I have to ask my professor to get in touch with his contact in ESA to access to this user and password or if there is any way to have the permissions to bootstrap correctly?

**Comment by levingerdes** [comment]
Hi @emichester,

unfortunately we cannot make the `autonav_interface` repository public but luckily you don't need it for the `stereo` / `dem_generation` packages (or any others really, it's a very high-level package). I will remove the references to it from our package set so that bootstrapping should not be blocked by missing permissions anymore. Thanks for pointing that out!

You can also consider using the official [rock buildconf](https://github.com/rock-core/buildconf) of course and only add the possibly few packages you actually need instead of using our entire setup all at once.

By the way, while we have looked into newer Ubuntu releases, we have only run our packages on Ubuntu 16.04 so far. Hopefully this helps avoid some headaches.

I hope this clarifies things a bit. I'll return to this issue once the package set has been updated.

**Comment by levingerdes** [comment]
Please give it another try and let us know whether the error persists.
